### ISSUE TITLE
Suggestion for form structure and styling

### ISSUE THREAD

**Issue by mhaidarhanif** [fahriabdhakim/fahriabdhakim.github.io#3]
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="./index.css">
  <title>Document</title>
</head>

<body>

  <div class="container">

    <main class="content">

      <form class="special-form">

        <div class="group">
          <label for="input-email">Email address</label>
          <input type="email" class="control" id="input-email" aria-describedby="emailHelp" placeholder="Enter email">
        </div>

        <div class="group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="control" id="exampleInputPassword1" placeholder="Password">
        </div>

        <div class="group">
          <input type="submit"></input>
        </div>

      </form>

    </main>

  </div>

</body>

</html>
```

```css
.special-form {
  width: 400px;
}

label, input {
  display: block;
  margin: 5px 0;
}

.group {
  margin: 10px 0;
}

input[type="submit"] {
  width: 100%;
}
```
